// <auto-generated />
using System;
using Billing.Api.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Billing.Api.Migrations
{
    [DbContext(typeof(BillingDbContext))]
    [Migration("20260205195616_InitialBillingSchema")]
    partial class InitialBillingSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Billing.Api.Domain.Entities.Bill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AdvanceAmount")
                        .HasColumnType("numeric");

                    b.Property<decimal>("BalanceAmount")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("BillDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("BillNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CustomerId")
                        .HasColumnType("integer");

                    b.Property<decimal>("DiscountAmount")
                        .HasColumnType("numeric");

                    b.Property<bool>("IsCleared")
                        .HasColumnType("boolean");

                    b.Property<decimal>("SubTotalAmount")
                        .HasColumnType("numeric");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("BillNumber")
                        .IsUnique();

                    b.HasIndex("CustomerId");

                    b.ToTable("Bills");
                });

            modelBuilder.Entity("Billing.Api.Domain.Entities.BillItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BillId")
                        .HasColumnType("integer");

                    b.Property<int?>("LaminationFinishId")
                        .HasColumnType("integer");

                    b.Property<int?>("LaminationTypeId")
                        .HasColumnType("integer");

                    b.Property<int>("PhotoServiceId")
                        .HasColumnType("integer");

                    b.Property<int>("PhotoSizeId")
                        .HasColumnType("integer");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("numeric(10,2)");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("numeric(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("BillId");

                    b.HasIndex("LaminationFinishId");

                    b.HasIndex("LaminationTypeId");

                    b.HasIndex("PhotoServiceId");

                    b.HasIndex("PhotoSizeId");

                    b.ToTable("BillItems");
                });

            modelBuilder.Entity("Billing.Api.Domain.Entities.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("PhoneNumber")
                        .IsUnique();

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("Billing.Api.Domain.Entities.LaminationFinish", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("LaminationFinishes");
                });

            modelBuilder.Entity("Billing.Api.Domain.Entities.LaminationFinishPrice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("ExtraPrice")
                        .HasColumnType("numeric(10,2)");

                    b.Property<int>("LaminationFinishId")
                        .HasColumnType("integer");

                    b.Property<int>("PhotoSizeId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("LaminationFinishId");

                    b.HasIndex("PhotoSizeId");

                    b.ToTable("LaminationFinishPrices");
                });

            modelBuilder.Entity("Billing.Api.Domain.Entities.LaminationType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("LaminationTypes");
                });

            modelBuilder.Entity("Billing.Api.Domain.Entities.PhotoPricing", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("BasePrice")
                        .HasColumnType("numeric(10,2)");

                    b.Property<decimal>("ExtraCopyPrice")
                        .HasColumnType("numeric(10,2)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int>("MinimumCopies")
                        .HasColumnType("integer");

                    b.Property<int>("PhotoServiceId")
                        .HasColumnType("integer");

                    b.Property<int>("PhotoSizeId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PhotoServiceId");

                    b.HasIndex("PhotoSizeId");

                    b.ToTable("PhotoPricings");
                });

            modelBuilder.Entity("Billing.Api.Domain.Entities.PhotoService", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("PhotoServices");
                });

            modelBuilder.Entity("Billing.Api.Domain.Entities.PhotoSize", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("PhotoSizes");
                });

            modelBuilder.Entity("Billing.Api.Domain.Entities.Bill", b =>
                {
                    b.HasOne("Billing.Api.Domain.Entities.Customer", "Customer")
                        .WithMany("Bills")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("Billing.Api.Domain.Entities.BillItem", b =>
                {
                    b.HasOne("Billing.Api.Domain.Entities.Bill", "Bill")
                        .WithMany("Items")
                        .HasForeignKey("BillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Billing.Api.Domain.Entities.LaminationFinish", "LaminationFinish")
                        .WithMany()
                        .HasForeignKey("LaminationFinishId");

                    b.HasOne("Billing.Api.Domain.Entities.LaminationType", "LaminationType")
                        .WithMany()
                        .HasForeignKey("LaminationTypeId");

                    b.HasOne("Billing.Api.Domain.Entities.PhotoService", "PhotoService")
                        .WithMany()
                        .HasForeignKey("PhotoServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Billing.Api.Domain.Entities.PhotoSize", "PhotoSize")
                        .WithMany()
                        .HasForeignKey("PhotoSizeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bill");

                    b.Navigation("LaminationFinish");

                    b.Navigation("LaminationType");

                    b.Navigation("PhotoService");

                    b.Navigation("PhotoSize");
                });

            modelBuilder.Entity("Billing.Api.Domain.Entities.LaminationFinishPrice", b =>
                {
                    b.HasOne("Billing.Api.Domain.Entities.LaminationFinish", "LaminationFinish")
                        .WithMany()
                        .HasForeignKey("LaminationFinishId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Billing.Api.Domain.Entities.PhotoSize", "PhotoSize")
                        .WithMany()
                        .HasForeignKey("PhotoSizeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LaminationFinish");

                    b.Navigation("PhotoSize");
                });

            modelBuilder.Entity("Billing.Api.Domain.Entities.PhotoPricing", b =>
                {
                    b.HasOne("Billing.Api.Domain.Entities.PhotoService", "PhotoService")
                        .WithMany()
                        .HasForeignKey("PhotoServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Billing.Api.Domain.Entities.PhotoSize", "PhotoSize")
                        .WithMany()
                        .HasForeignKey("PhotoSizeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PhotoService");

                    b.Navigation("PhotoSize");
                });

            modelBuilder.Entity("Billing.Api.Domain.Entities.Bill", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("Billing.Api.Domain.Entities.Customer", b =>
                {
                    b.Navigation("Bills");
                });
#pragma warning restore 612, 618
        }
    }
}
